### ISSUE TITLE
Why ?

### ISSUE THREAD

**Issue by xxLG30xx** [ArcadeTV/megadrive-samples#1]
Hi to you,
I just realized that your magnificent work was no longer there. I wanted to take the Sunset Riders patch and there are only the two patches left for Sonic. You stop the patches or you host them elsewhere. Thanks for your return.

**Comment by ArcadeTV** [comment]
The Sonic disassemblies are forks and I couldn't set them to private. They are due to be unpublished too. The reason is that I'm not willing to take any more insults from people who try to talk me into fixing, releasing or porting stuff asap as if I ran a business. 
Maybe the patches will come back some day, for now I've had it. Thank you for your support.
